import path from "node:path";
import { defineConfig } from "wxt";
import tailwindcss from "@tailwindcss/vite";

const FRONTEND_SRC = path.resolve(__dirname, "../frontend/src");

// Build flavor, selected by the KODO_FLAVOR env var (see lib/flavor.ts). "dhis2" ships the
// "kodo for DHIS2" build (branded name/description + DHIS2 copy) into its own output dir so
// both flavors can be built side by side; anything else is the neutral generic build. Only
// name/description/title and a few words of in-app copy differ — every feature is in both.
const FLAVOR = process.env.KODO_FLAVOR === "dhis2" ? "dhis2" : "generic";
const IS_DHIS2 = FLAVOR === "dhis2";

const MANIFEST_NAME = IS_DHIS2 ? "kodo for DHIS2" : "kodo";
const MANIFEST_DESCRIPTION = IS_DHIS2
  ? "Your local AI assistant for DHIS2 - chat, verify, and act on your instance with your own model"
  : "Side panel for your local kodo assistant";

// Per-flavor toolbar/store icons (generated by scripts/gen-icons.ts into public/icon/, copied
// verbatim by WXT). The dhis2 set carries a small blue corner accent; the generic set is a plain
// dark mark. Both are the same "k" glyph.
const ICON_PREFIX = IS_DHIS2 ? "dhis2" : "generic";
const MANIFEST_ICONS = {
  "16": `icon/${ICON_PREFIX}-16.png`,
  "32": `icon/${ICON_PREFIX}-32.png`,
  "48": `icon/${ICON_PREFIX}-48.png`,
  "128": `icon/${ICON_PREFIX}-128.png`,
};

// The extension reuses the shared frontend source (frontend/src/{api,lib,components}),
// where "@/..." resolves to frontend/src — both for the modules the panel imports and
// for the imports those modules make of each other. WXT forces "@" -> its own srcDir
// (the extension root) via a Vite plugin; the redirect below reclaims "@" for the
// shared source (see the hooks block). No extension-local code uses "@" to mean the
// extension root, so this is safe.
export default defineConfig({
  modules: ["@wxt-dev/module-react"],
  // The generic build keeps the default `.output/chrome-mv3`; the dhis2 build lands in
  // `.output/chrome-mv3-dhis2` so both can coexist and the E2E/screenshots tooling can pick
  // one. The `{{modeSuffix}}` keeps `-dev` on the WXT dev server output as usual.
  ...(IS_DHIS2 ? { outDirTemplate: "{{browser}}-mv{{manifestVersion}}-dhis2{{modeSuffix}}" } : {}),
  vite: () => ({
    plugins: [tailwindcss()],
    // Bake the flavor into the bundle so app code (lib/flavor.ts) can branch copy on it.
    define: { __KODO_FLAVOR__: JSON.stringify(FLAVOR) },
    resolve: {
      dedupe: ["react", "react-dom"],
    },
  }),
  // Redirect the "@" alias to the shared frontend source. WXT forces
  // "@" -> srcDir via its own Vite plugin (wxt:aliases), and Vite applies plugin
  // config() results as overrides in plugin order, so a plain user alias always
  // loses. We append a plugin to the final per-entrypoint config (in the
  // vite:build:extendConfig hook) so its config() runs LAST and wins. No
  // extension-local code uses "@" to mean the extension root, so this is safe.
  hooks: {
    "vite:build:extendConfig": (_entrypoints, config) => {
      config.plugins ??= [];
      config.plugins.push({
        name: "kodo:at-alias-to-frontend",
        config: () => ({ resolve: { alias: { "@": FRONTEND_SRC } } }),
      });
    },
  },
  manifest: {
    name: MANIFEST_NAME,
    description: MANIFEST_DESCRIPTION,
    icons: MANIFEST_ICONS,
    permissions: ["sidePanel", "storage", "tabs", "activeTab", "scripting"],
    // Requested on demand during the session-fallback bind consent (user gesture), so kodo can read
    // and re-sync the target site's session cookie. Not in the base grant — most users only ever mint
    // a scoped PAT, which needs no cookie access.
    optional_permissions: ["cookies"],
    optional_host_permissions: ["http://*/*", "https://*/*"],
    host_permissions: ["http://127.0.0.1/*", "http://localhost/*"],
    side_panel: { default_path: "sidepanel.html" },
    action: { default_title: MANIFEST_NAME },
  },
});
