"""Regenerate the terminal-chat startup logo from the project logo.

Reads ``docs/assets/logo.png``, downsamples it to a small pixel grid, and writes
``src/stabbur/chat_tui/_logo.py`` with the grid embedded as data plus the
half-block renderer. The TUI therefore needs no image library and no asset file
at runtime; a color-capable terminal renders the badge, everything else
degrades through Rich's normal color downconversion.

Run with: uv run --with pillow python scripts/gen_tui_logo.py
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

SIZE = 16  # grid is SIZE x SIZE pixels -> SIZE columns x SIZE/2 terminal rows
ALPHA_OPAQUE = 128  # below this a pixel falls through to the terminal background

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "assets" / "logo.png"
TARGET = ROOT / "src" / "stabbur" / "chat_tui" / "_logo.py"

HEADER = '''"""The startup badge for the terminal chat, as a tiny pixel grid.

GENERATED by scripts/gen_tui_logo.py from docs/assets/logo.png - do not edit by
hand; rerun the script after changing the logo. Each cell is a hex color or
None for transparent; the renderer packs two grid rows into one terminal row of
half blocks, so the terminal draws square-ish pixels with no image support
needed.
"""

from __future__ import annotations

from rich.text import Text

'''

FOOTER = '''

def logo_text() -> Text:
    """Render the grid as half-block art; transparent cells show the terminal ground."""
    art = Text()
    for top_row, bottom_row in zip(LOGO_ROWS[0::2], LOGO_ROWS[1::2], strict=True):
        if art.plain:
            art.append("\\n")
        for top, bottom in zip(top_row, bottom_row, strict=True):
            if top and bottom:
                art.append("\\u2580", style=f"{top} on {bottom}")
            elif top:
                art.append("\\u2580", style=top)
            elif bottom:
                art.append("\\u2584", style=bottom)
            else:
                art.append(" ")
    return art
'''


def main() -> None:
    """Downsample the logo and write the embedded grid module."""
    image = Image.open(SOURCE).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    pixels = image.load()
    assert pixels is not None

    rows: list[str] = []
    for y in range(SIZE):
        cells: list[str] = []
        for x in range(SIZE):
            r, g, b, a = pixels[x, y]
            cells.append(f'"#{r:02x}{g:02x}{b:02x}"' if a >= ALPHA_OPAQUE else "None")
        rows.append("    (" + ", ".join(cells) + "),")

    body = "LOGO_ROWS: tuple[tuple[str | None, ...], ...] = (\n" + "\n".join(rows) + "\n)\n"
    TARGET.write_text(HEADER + body + FOOTER)
    print(f"wrote {TARGET.relative_to(ROOT)} ({SIZE}x{SIZE})")


if __name__ == "__main__":
    main()
